!obj:pylearn2.train.Train
{
    dataset: &train !obj:datasets.cin_feature2_composite.CIN_FEATURE850_2
        {
            which_set: 'train',
            foldi: %(foldi)d
        },

    model: !obj:pylearn2.models.mlp.MLP
    {
        batch_size: 1140,
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: %(dim_h0)i,
                     sparse_init: 15
                 }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: %(dim_h1)i,
                     sparse_init: 15
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 2,
                     irange: 0.
                 }
                ],
        nvis: %(nvis)i,
    },

    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD
    {
        line_search_mode: 'exhaustive',
        conjugate: 1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:datasets.cin_feature2_composite.CIN_FEATURE850_2
                {
                    which_set: 'valid',
                    foldi: %(foldi)d
                },
                'test' : !obj:datasets.cin_feature2_composite.CIN_FEATURE850_2
                {
                    which_set: 'test',
                    foldi: %(foldi)d
                },
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts
        {
            costs:
            [
                    !obj:pylearn2.costs.mlp.Default { },
                    !obj:pylearn2.costs.mlp.WeightDecay
                    {
                        coeffs: [ .0005, .0005, .0005 ]
                    }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass",
                    prop_decrease: 0.,
                    N: 10
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: %(max_epochs)i
                }
            ]
        }
    },
    extensions: [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)s"
        },
    ]
}
