!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.scripts.med_ml.cin_feature2.CIN_FEATURE2
        {
            which_set: 'train',
            datapath: %(data_path)s
        },

    model: !obj:pylearn2.models.mlp.MLP {
        layers:
        [
            !obj:pylearn2.models.mlp.PretrainedLayer
            {
                layer_name: 'h01',
                layer_content: !pkl: "mlp4_1700.1700-on-feature850-2-1.pkl"
            },
            !obj:pylearn2.models.mlp.RectifiedLinear
            {
                layer_name: 'h2',
                dim: %(dim_h2)i,
                sparse_init: %(sparse_init_h1)i
            },
            !obj:pylearn2.models.mlp.Softmax
            {
                layer_name: 'y',
                n_classes: 2,
                irange: 0.
            }
        ],
        nvis: 850,
    },

    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD
    {
        batch_size: 1140,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:pylearn2.scripts.med_ml.cin_feature2.CIN_FEATURE2
                {
                    which_set: 'valid',
                    datapath: %(data_path)s
                },
                'test' : !obj:pylearn2.scripts.med_ml.cin_feature2.CIN_FEATURE2
                {
                    which_set: 'test',
                    datapath: %(data_path)s
                },
            },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass",
                    prop_decrease: 0.,
                    N: 10
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: %(max_epochs)i
                }
            ]
        }
    },
    extensions: [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)s"
        },
    ]
}
